### ISSUE TITLE
Features / TODO

### ISSUE THREAD

**Issue by tandav** [tandav/Henon-Map#3]
- [ ] Start w/ pixels but then add resizable charts [responsive charts d3 - Google Search](https://www.google.com/search?q=responsive+charts+d3&oq=responsive+chart&aqs=chrome.2.0j69i57j0l4.5726j0j7&sourceid=chrome&ie=UTF-8)
    - responsive svg, viewbox
    - на мобиле - просто показывать один график `xy_plot`
- [ ] when change by sliders show (a, b) pointer on a plot
- [ ] litlle documentation online
  - in my own simple words
- [ ] KaTex formulas (Khan Academy)
- [ ] В будущем добавить возможность строить свои формулы
- [ ] ability to edit initial `[x0, y0]`
- [x] add scale sliders (zoom)
  - trackpad / scroll zoom?
  - [Pan & Zoom Axes - bl.ocks.org](https://bl.ocks.org/mbostock/db6b4335bf1662b413e7968910104f0f)  
- [ ] checkbox: show axes
- [ ] Numeric UpDown for better precision
- [ ] ability to tweet picture ? 
- [ ] у меня типа просто удаляются старые точки и рисуются новые, это типа вообще зашквар по производительности (DOM redraw). Юзай / Гугли `D3 Update `
- [ ] simplify `script.js` (use functions)
- [ ] probably xn and yn plots works with bugs (they seems equal)
  - to compare draw x(n) and y(n) on one chart with different colors
- [ ] add labels for axes
- [x] Disable mouse-hover button
- Мб отдельный XY controller для a, b? Просто ща на одном вместе с xy и при зуме могут быть проблемы. Можно типа один просто mouse_move, другой mouse_move с нажатием
- мб add control by arrow keys
- [ ] del useless arr {} 
- [ ] походу нужно переделать на canvas for better performance 

## Future
- render more points when zoom
  - сложно, потому что формула не позволяет просчитать конкретную область. Можно просто если "простой CPU" / stable ab - просчитывать в фоне и добавлять точки. Но когда меняешь ab - для скорости работы брать меньше точек (200-300)
- More consistent coloring (design)
## Bugs
- [ ] fix margins and axis margins
## Afterall
- [ ] залить на http://bl.ocks.org
- [ ] залить пару видюх на yt (like a demo )
- [ ] release on HN, reddit

**Comment by tandav** [comment]
# Maybe
- [Simple Single Axis Zoom - bl.ocks.org](http://bl.ocks.org/jgbos/9752277)
- try to connect the points (test it in python)

**Comment by tandav** [comment]
на стрелочках for better precision

**Comment by tandav** [comment]
press t to tweet image (need server)

**Comment by tandav** [comment]
press space to turn off dragging (чтобы курсор не сбился)
